name: 🧪 Functional Test

on:
  pull_request:
    paths:
      - '**.go'
  workflow_dispatch:


jobs:  
  functional-test:
    if: "! endsWith(github.actor, '[bot]')"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: projectdiscovery/actions/setup/go@v1

      - name: Functional Tests
        env:
          GH_ACTION: true
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          chmod +x run.sh
          bash run.sh ${{ matrix.os }}
        working-directory: cmd/functional-test
